import React from "react"
import styled from "styled-components"
import WikiLayout from "../../components/layout.js"
import ScrollProgress from "../../components/scrollProgress.js"
import TableOfContents from "../../components/tableOfContents.js"

const Page = () => (
  <WikiLayout pageTitle="Pivotal Changes and Milestones">
    <ScrollProgress> </ScrollProgress>
    <TableOfContents />
    <div id="page-content">
      <h1>Heading 1</h1>
      <p>Swat turds around the house paw at beetle and eat it before it gets away. Litter box is life under the bed, or meow for food, then when human fills food dish, take a few bites of food and continue meowing but sit by the fire leave fur on owners clothes, so cat is love, cat is life. More napping, more napping all the napping is exhausting loved it, hated it, loved it, hated it kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment walk on car leaving trail of paw prints on hood and windshield, yet cattt catt cattty cat being a cat. Fight own tail pelt around the house and up and down stairs chasing phantoms cat fur is the new black gimme attention gimme attention gimme attention gimme attention gimme attention gimme attention just kidding i don't want it anymore meow bye. Take a big fluffing crap ðŸ’© see owner, run in terror toilet paper attack claws fluff everywhere meow miao french ciao litterbox purr when being pet climb a tree, wait for a fireman jump to fireman then scratch his face yet catch small lizards, bring them into house, then unable to find them on carpet.</p>
      <h1>Heading 2</h1>
      <p>Swat turds around the house paw at beetle and eat it before it gets away. Litter box is life under the bed, or meow for food, then when human fills food dish, take a few bites of food and continue meowing but sit by the fire leave fur on owners clothes, so cat is love, cat is life. More napping, more napping all the napping is exhausting loved it, hated it, loved it, hated it kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment walk on car leaving trail of paw prints on hood and windshield, yet cattt catt cattty cat being a cat. Fight own tail pelt around the house and up and down stairs chasing phantoms cat fur is the new black gimme attention gimme attention gimme attention gimme attention gimme attention gimme attention just kidding i don't want it anymore meow bye. Take a big fluffing crap ðŸ’© see owner, run in terror toilet paper attack claws fluff everywhere meow miao french ciao litterbox purr when being pet climb a tree, wait for a fireman jump to fireman then scratch his face yet catch small lizards, bring them into house, then unable to find them on carpet.</p>
      <h1>Heading 3</h1>
      <p>Swat turds around the house paw at beetle and eat it before it gets away. Litter box is life under the bed, or meow for food, then when human fills food dish, take a few bites of food and continue meowing but sit by the fire leave fur on owners clothes, so cat is love, cat is life. More napping, more napping all the napping is exhausting loved it, hated it, loved it, hated it kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment walk on car leaving trail of paw prints on hood and windshield, yet cattt catt cattty cat being a cat. Fight own tail pelt around the house and up and down stairs chasing phantoms cat fur is the new black gimme attention gimme attention gimme attention gimme attention gimme attention gimme attention just kidding i don't want it anymore meow bye. Take a big fluffing crap ðŸ’© see owner, run in terror toilet paper attack claws fluff everywhere meow miao french ciao litterbox purr when being pet climb a tree, wait for a fireman jump to fireman then scratch his face yet catch small lizards, bring them into house, then unable to find them on carpet.</p>
      <h1>Heading 4</h1>
      <p>Swat turds around the house paw at beetle and eat it before it gets away. Litter box is life under the bed, or meow for food, then when human fills food dish, take a few bites of food and continue meowing but sit by the fire leave fur on owners clothes, so cat is love, cat is life. More napping, more napping all the napping is exhausting loved it, hated it, loved it, hated it kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment walk on car leaving trail of paw prints on hood and windshield, yet cattt catt cattty cat being a cat. Fight own tail pelt around the house and up and down stairs chasing phantoms cat fur is the new black gimme attention gimme attention gimme attention gimme attention gimme attention gimme attention just kidding i don't want it anymore meow bye. Take a big fluffing crap ðŸ’© see owner, run in terror toilet paper attack claws fluff everywhere meow miao french ciao litterbox purr when being pet climb a tree, wait for a fireman jump to fireman then scratch his face yet catch small lizards, bring them into house, then unable to find them on carpet.</p>
      <h1>Heading 5</h1>
      <p>Swat turds around the house paw at beetle and eat it before it gets away. Litter box is life under the bed, or meow for food, then when human fills food dish, take a few bites of food and continue meowing but sit by the fire leave fur on owners clothes, so cat is love, cat is life. More napping, more napping all the napping is exhausting loved it, hated it, loved it, hated it kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment walk on car leaving trail of paw prints on hood and windshield, yet cattt catt cattty cat being a cat. Fight own tail pelt around the house and up and down stairs chasing phantoms cat fur is the new black gimme attention gimme attention gimme attention gimme attention gimme attention gimme attention just kidding i don't want it anymore meow bye. Take a big fluffing crap ðŸ’© see owner, run in terror toilet paper attack claws fluff everywhere meow miao french ciao litterbox purr when being pet climb a tree, wait for a fireman jump to fireman then scratch his face yet catch small lizards, bring them into house, then unable to find them on carpet.</p>
      <h1>Heading 6</h1>
      <p>Swat turds around the house paw at beetle and eat it before it gets away. Litter box is life under the bed, or meow for food, then when human fills food dish, take a few bites of food and continue meowing but sit by the fire leave fur on owners clothes, so cat is love, cat is life. More napping, more napping all the napping is exhausting loved it, hated it, loved it, hated it kitty pounce, trip, faceplant you didn't see that no you didn't definitely didn't lick, lick, lick, and preen away the embarrassment walk on car leaving trail of paw prints on hood and windshield, yet cattt catt cattty cat being a cat. Fight own tail pelt around the house and up and down stairs chasing phantoms cat fur is the new black gimme attention gimme attention gimme attention gimme attention gimme attention gimme attention just kidding i don't want it anymore meow bye. Take a big fluffing crap ðŸ’© see owner, run in terror toilet paper attack claws fluff everywhere meow miao french ciao litterbox purr when being pet climb a tree, wait for a fireman jump to fireman then scratch his face yet catch small lizards, bring them into house, then unable to find them on carpet.</p>
    </div>
  </WikiLayout>
)
export default Page
export const Head = () => <title>Pivotal Changes and Milestones — iGEM Toronto 2026</title>
const Placeholder = styled.div`
  border: 1px dashed var(--color-border); border-radius: 4px;
  padding: var(--space-xl); color: var(--color-muted); text-align: center; font-size: 1.1rem;
  strong { color: var(--color-accent); }
`
